<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="webTests.promotionCreationTests.transactionLevelDisscountTests.FlatAmountDiscountOnTransactionTests" tests="1" time="0.100" ignored="1" failures="0" timestamp="02 May 2017 09:34:50 GMT" skipped="0" hostname="User-PC" errors="1">
  <testcase name="dealCreationForTransactionLevelDiscount" time="0.100" classname="webTests.promotionCreationTests.transactionLevelDisscountTests.FlatAmountDiscountOnTransactionTests">
    <error type="java.lang.ArrayIndexOutOfBoundsException" message="18">
      <![CDATA[java.lang.ArrayIndexOutOfBoundsException: 18
	at pageAction.promotionCreationMethods.CreateDealMethods.creatingDeal(CreateDealMethods.java:52)
	at webTests.promotionCreationTests.transactionLevelDisscountTests.FlatAmountDiscountOnTransactionTests.dealCreationForTransactionLevelDiscount(FlatAmountDiscountOnTransactionTests.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </error>
  </testcase> <!-- dealCreationForTransactionLevelDiscount -->
  <testcase name="createPromotionForTransactionLevel" classname="webTests.promotionCreationTests.transactionLevelDisscountTests.FlatAmountDiscountOnTransactionTests">
    <skipped/>
  </testcase> <!-- createPromotionForTransactionLevel -->
</testsuite> <!-- webTests.promotionCreationTests.transactionLevelDisscountTests.FlatAmountDiscountOnTransactionTests -->
